# Generated by Django 4.2.13 on 2025-08-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCode',
        ),
    ]
